# Generated by Django 5.2.2 on 2025-06-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Corporativo', 'Corporativo'), ('Religioso', 'Religioso'), ('Intercâmbio', 'Intercâmbio'), ('Lazer', 'Lazer')], max_length=20)),
                ('imagem', models.ImageField(upload_to='box_produtos/')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=250)),
                ('link', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=300)),
                ('imagem', models.ImageField(upload_to='slides/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='unidades/')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('link', models.URLField()),
            ],
        ),
    ]
