# Generated by Django 5.2.2 on 2025-06-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadora', '0003_slide_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
