# Generated by Django 5.2.2 on 2025-06-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadora', '0004_slide_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
