# Generated by Django 5.2.2 on 2025-06-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadora', '0005_emailnotificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='icone',
            field=models.CharField(blank=True, choices=[('fas fa-book', 'Livro'), ('fas fa-map', 'Mapa'), ('fas fa-globe', 'Globo'), ('fas fa-plane', 'Avião'), ('fas fa-mountain', 'Montanha'), ('fas fa-file-pdf', 'PDF'), ('fas fa-umbrella-beach', 'Praia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='roteiros/thumbnails/'),
        ),
    ]
