# Generated by Django 5.2.2 on 2025-06-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadora', '0006_roteiro_icone_alter_roteiro_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerRoteiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_pc', models.ImageField(blank=True, help_text='1920x500 para desktop e tablet', null=True, upload_to='banners/roteiros/')),
                ('imagem_mobile', models.ImageField(blank=True, help_text='480x720 para mobile', null=True, upload_to='banners/roteiros/')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
