# Generated by Django 5.2.2 on 2025-06-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operadora', '0009_bannerroteiros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerRoteiros',
        ),
        migrations.DeleteModel(
            name='Roteiro',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.DeleteModel(
            name='VideoAula',
        ),
    ]
