# Generated by Django 4.2.22 on 2025-06-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operadora', '0011_roteiro_slide_videoaula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roteiro',
            options={'verbose_name': 'Roteiros'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='videoaula',
            options={'verbose_name': 'Aulas'},
        ),
    ]
