# Generated by Django 4.2.22 on 2025-06-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operadora', '0012_alter_roteiro_options_alter_slide_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roteiro',
            options={'verbose_name': 'Roteiro'},
        ),
        migrations.AlterModelOptions(
            name='videoaula',
            options={'verbose_name': 'Aula'},
        ),
    ]
