# Generated by Django 4.2.22 on 2025-06-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operadora', '0013_alter_roteiro_options_alter_videoaula_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
    ]
