# Generated by Django 4.2.22 on 2025-06-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadora', '0014_alter_slide_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='banners/aulas/')),
                ('categoria', models.CharField(choices=[('terra_santa', 'Terra Santa'), ('treinamento', 'Treinamento Empresarial'), ('dubai', 'Dubai'), ('eua', 'Estados Unidos')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BannerDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='banners/downloads/')),
            ],
        ),
        migrations.CreateModel(
            name='BannerFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='banners/fornecedores/')),
            ],
        ),
        migrations.CreateModel(
            name='BannerManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='banners/manuais/')),
            ],
        ),
        migrations.CreateModel(
            name='BannerProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='banners/produtos/')),
            ],
        ),
        migrations.CreateModel(
            name='BannerRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='banners/roteiros/')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='downloads/')),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
