# Generated by Django 4.2.22 on 2025-06-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadora', '0015_banneraula_bannerdownload_bannerfornecedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerroteiro',
            name='imagem',
        ),
        migrations.AddField(
            model_name='bannerroteiro',
            name='banner_mobile',
            field=models.ImageField(blank=True, help_text='480x720 para celular', null=True, upload_to='banners/roteiros/'),
        ),
        migrations.AddField(
            model_name='bannerroteiro',
            name='banner_pc',
            field=models.ImageField(blank=True, help_text='1920x500 para desktop e tablet', null=True, upload_to='banners/roteiros/'),
        ),
    ]
