# Generated by Django 4.2.22 on 2025-06-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadora', '0016_remove_bannerroteiro_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerfornecedor',
            name='imagem',
        ),
        migrations.AddField(
            model_name='bannerfornecedor',
            name='banner_mobile',
            field=models.ImageField(blank=True, help_text='480x720 para celular', null=True, upload_to='banners/fornecedores/'),
        ),
        migrations.AddField(
            model_name='bannerfornecedor',
            name='banner_pc',
            field=models.ImageField(blank=True, help_text='1920x500 para desktop e tablet', null=True, upload_to='banners/fornecedores/'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='pais',
            field=models.CharField(blank=True, max_length=100, verbose_name='País de origem'),
        ),
    ]
